export const pageIndexSetting = [
	{ path: 'pages/index/index', index: 1 },
	{ path: 'pages/shop/shop', index: 2 },
	{ path: 'pages/discovery/discovery', index: 3 },
	{ path: 'pages/mine/mine', index: 4 },
	{ path: 'pages/goods/index', index: 5 },
	{ path: 'pages/pay-order/pay-order', index: 6 },
	{ path: 'pages/bind-blank-card/bind-blank-card', index: 7 },
	{ path: 'pages/add-blank-info/add-blank-info', index: 8 },
	{ path: 'pages/check-blank-code/check-blank-code', index: 9 },
	{ path: 'pages/set-pwd/set-pwd', index: 10 },
	{ path: 'pages/pay-check/pay-check', index: 11 },
	{ path: 'pages/pay-success/pay-success', index: 11 },
	{ path: 'pages/order/index', index: 11 },
	{ path: 'pages/address/address', index: 11 },
	{ path: 'pages/address/adressadd', index: 11 },
	{ path: 'pages/address/adressedit', index: 11 },
	{ path: 'pages/activity/activity', index: 11 },
	{ path: 'pages/goodsevaluate/index', index: 11 },
	{ path: 'pages/deal/deal', index: 20 },

	// {path:'',index:},
	// {path:'',index:},
]
